import { Product, User } from '@/types';

// Mock products for pet supply inventory
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Premium Dog Food 15kg',
    category: 'food',
    stock: 45,
    minStock: 20,
    price: 59.99,
    supplier: 'Pet Nutrition Co.',
    lastUpdated: new Date(),
  },
  {
    id: '2',
    name: 'Cat Litter Box',
    category: 'accessories',
    stock: 12,
    minStock: 15,
    price: 34.99,
    supplier: 'Feline Essentials',
    lastUpdated: new Date(),
  },
  {
    id: '3',
    name: 'Squeaky Dog Toy Set',
    category: 'toys',
    stock: 78,
    minStock: 30,
    price: 19.99,
    supplier: 'Happy Paws Inc.',
    lastUpdated: new Date(),
  },
  {
    id: '4',
    name: 'Flea & Tick Treatment',
    category: 'healthcare',
    stock: 5,
    minStock: 10,
    price: 44.99,
    supplier: 'Vet Solutions',
    lastUpdated: new Date(),
  },
  {
    id: '5',
    name: 'Cat Food - Salmon Flavor 5kg',
    category: 'food',
    stock: 32,
    minStock: 25,
    price: 42.99,
    supplier: 'Feline Gourmet',
    lastUpdated: new Date(),
  },
  {
    id: '6',
    name: 'Pet Grooming Brush',
    category: 'grooming',
    stock: 0,
    minStock: 20,
    price: 15.99,
    supplier: 'Grooming Pros',
    lastUpdated: new Date(),
  },
  {
    id: '7',
    name: 'Retractable Dog Leash',
    category: 'accessories',
    stock: 56,
    minStock: 25,
    price: 28.99,
    supplier: 'Walk Masters',
    lastUpdated: new Date(),
  },
  {
    id: '8',
    name: 'Bird Seed Mix 2kg',
    category: 'food',
    stock: 8,
    minStock: 15,
    price: 12.99,
    supplier: 'Aviary Supply Co.',
    lastUpdated: new Date(),
  },
  {
    id: '9',
    name: 'Aquarium Water Conditioner',
    category: 'healthcare',
    stock: 23,
    minStock: 10,
    price: 9.99,
    supplier: 'Aqua Solutions',
    lastUpdated: new Date(),
  },
  {
    id: '10',
    name: 'Rabbit Hutch Bedding',
    category: 'accessories',
    stock: 14,
    minStock: 20,
    price: 16.99,
    supplier: 'Small Pet Supplies',
    lastUpdated: new Date(),
  },
];

// Mock users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    role: 'admin',
    online: true,
  },
  {
    id: '2',
    name: 'Store Manager',
    role: 'staff',
    online: true,
  },
  {
    id: '3',
    name: 'Customer Support',
    role: 'staff',
    online: false,
  },
];
