import { Product, User } from '@/types';

// Productos de ejemplo para inventario de mascotas
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Alimento Premium para Perros 15kg',
    category: 'food',
    stock: 45,
    minStock: 20,
    price: 189000,
    supplier: 'Nutripet Colombia',
    lastUpdated: new Date(),
  },
  {
    id: '2',
    name: 'Caja de Arena para Gatos',
    category: 'accessories',
    stock: 12,
    minStock: 15,
    price: 85000,
    supplier: 'Felinos Esenciales',
    lastUpdated: new Date(),
  },
  {
    id: '3',
    name: 'Set de Juguetes para Perros',
    category: 'toys',
    stock: 78,
    minStock: 30,
    price: 45000,
    supplier: 'Mascotas Felices SAS',
    lastUpdated: new Date(),
  },
  {
    id: '4',
    name: 'Tratamiento Antipulgas y Garrapatas',
    category: 'healthcare',
    stock: 5,
    minStock: 10,
    price: 95000,
    supplier: 'Veterinaria Central',
    lastUpdated: new Date(),
  },
  {
    id: '5',
    name: 'Alimento para Gatos Sabor Salmón 5kg',
    category: 'food',
    stock: 32,
    minStock: 25,
    price: 125000,
    supplier: 'Gourmet Felino',
    lastUpdated: new Date(),
  },
  {
    id: '6',
    name: 'Cepillo para Mascotas',
    category: 'grooming',
    stock: 0,
    minStock: 20,
    price: 35000,
    supplier: 'Peluquería Canina',
    lastUpdated: new Date(),
  },
  {
    id: '7',
    name: 'Correa Retráctil para Perros',
    category: 'accessories',
    stock: 56,
    minStock: 25,
    price: 68000,
    supplier: 'Paseos Seguros',
    lastUpdated: new Date(),
  },
  {
    id: '8',
    name: 'Semillas para Aves 2kg',
    category: 'food',
    stock: 8,
    minStock: 15,
    price: 28000,
    supplier: 'Aviario Colombia',
    lastUpdated: new Date(),
  },
  {
    id: '9',
    name: 'Acondicionador de Agua para Acuarios',
    category: 'healthcare',
    stock: 23,
    minStock: 10,
    price: 22000,
    supplier: 'Acuarios del Valle',
    lastUpdated: new Date(),
  },
  {
    id: '10',
    name: 'Virutas para Jaula de Conejos',
    category: 'accessories',
    stock: 14,
    minStock: 20,
    price: 38000,
    supplier: 'Pequeñas Mascotas',
    lastUpdated: new Date(),
  },
];

// Usuarios de ejemplo
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Administrador',
    role: 'admin',
    online: true,
  },
  {
    id: '2',
    name: 'Gerente de Tienda',
    role: 'staff',
    online: true,
  },
  {
    id: '3',
    name: 'Servicio al Cliente',
    role: 'staff',
    online: false,
  },
];
